version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.54.1
    container_name: prometheus
    network_mode: host
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: docker.io/grafana/grafana:11.2.2
    container_name: grafana
    network_mode: host
    volumes:
      - ./configs/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:Z
      - ./configs/inventory-service-dashboard.json:/etc/grafana/provisioning/dashboards/inventory-service-dashboard.json:Z
      - ./configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:Z
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jaeger-all-in-one:
    image: docker.io/jaegertracing/all-in-one:1.62.0
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP receiver

