---

services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:17.4
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGPASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "psql -U keycloak -d keycloak -c 'SELECT 1' || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    networks:
      - keycloak_network
    volumes:
      - quia-keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    user: "${UID}"
    volumes:
      - "./car-rental-realm.json:/opt/keycloak/data/import/car-rental-realm.json:Z"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 7777:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network

  adminer:
    image: adminer
    container_name: keycloak-adminer
    restart: always
    depends_on:
      postgres :
        condition: service_healthy
    ports:
      - 9090:8080
    networks:
      - keycloak_network

volumes:
  quia-keycloak-postgres:
    external: true
    name: quia-keycloak-postgres-17

networks:
  keycloak_network:
    driver: bridge

