{
 "title": "Inventory service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Eden Space\", instance=\"localhost:8083\", job=\"inventory-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Old Gen\", instance=\"localhost:8083\", job=\"inventory-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Car registrations & removals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "method_counted_total{method=\"register\"}"
    },
    {
     "expr": "method_counted_total{method=\"remove\"}"
    }
   ]
  },
  {
   "title": "Process uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}